# Generated by Django 3.0 on 2019-12-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('완성사진', models.ImageField(upload_to='recipeImages/')),
                ('이름', models.CharField(max_length=30, null=True)),
                ('재료', models.CharField(max_length=100, null=True)),
                ('레시피1_사진', models.ImageField(upload_to='recipeImages/')),
                ('레시피1', models.TextField()),
                ('레시피2_사진', models.ImageField(blank=True, upload_to='recipeImages/')),
                ('레시피2', models.TextField(blank=True)),
                ('레시피3_사진', models.ImageField(blank=True, upload_to='recipeImages/')),
                ('레시피3', models.TextField(blank=True)),
                ('레시피4_사진', models.ImageField(blank=True, upload_to='recipeImages/')),
                ('레시피4', models.TextField(blank=True)),
                ('레시피5_사진', models.ImageField(blank=True, upload_to='recipeImages/')),
                ('레시피5', models.TextField(blank=True)),
            ],
        ),
    ]
