# Generated by Django 3.0 on 2019-12-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='레시피10',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='main',
            name='레시피10_사진',
            field=models.ImageField(blank=True, upload_to='recipeImages/'),
        ),
        migrations.AddField(
            model_name='main',
            name='레시피6',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='main',
            name='레시피6_사진',
            field=models.ImageField(blank=True, upload_to='recipeImages/'),
        ),
        migrations.AddField(
            model_name='main',
            name='레시피7',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='main',
            name='레시피7_사진',
            field=models.ImageField(blank=True, upload_to='recipeImages/'),
        ),
        migrations.AddField(
            model_name='main',
            name='레시피8',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='main',
            name='레시피8_사진',
            field=models.ImageField(blank=True, upload_to='recipeImages/'),
        ),
        migrations.AddField(
            model_name='main',
            name='레시피9',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='main',
            name='레시피9_사진',
            field=models.ImageField(blank=True, upload_to='recipeImages/'),
        ),
    ]
